apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: kubeflow
data:
  config: |
    {
    executorImage: $(executorImage),
    artifactRepository:
    {
        archiveLogs: true,
        s3: {
            bucket: $(artifactRepositoryBucket),
            keyPrefix: $(artifactRepositoryKeyPrefix),
            endpoint: s3.amazonaws.com,
            insecure: false,
            accessKeySecret: {
                name: $(awsSecretName),
                key: $(awsAccessKeySecretKey)
            },
            secretKeySecret: {
                name: $(awsSecretName),
                key: $(awsSecretKeySecretKey)
            }
        }
    }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-ui
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline-ui
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: $(awsSecretName)
                  key: $(awsAccessKeySecretKey)
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: $(awsSecretName)
                  key: $(awsSecretKeySecretKey)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline-api-server
          env:
            - name: OBJECTSTORECONFIG_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: $(awsSecretName)
                  key: $(awsAccessKeySecretKey)
            - name: OBJECTSTORECONFIG_SECRETACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: $(awsSecretName)
                  key: $(awsSecretKeySecretKey)